### ISSUE TITLE
[FEATURE] cloud-init support

### ISSUE THREAD

**Issue by exocode** [davidferguson/pibakery#161]
It would be nice when V2 will implement/provide the widely used `cloud-init`tool. Maybe in form of a block, where the User can choose a customized "cloud-config.yaml"

Something like this:

```
#cloud-config
## run with --config
# vim: syntax=yaml
#
hostname: black-pearl
manage_etc_hosts: true

wifi:
  interfaces:
    wlan0:
      ssid: "UPC2463EF9"
      password: "zxhWsVb7j3cc"

users:
  - name: pirate
    gecos: "Hypriot Pirate"
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    groups: users,docker,video
    plain_text_passwd: hypriot
    lock_passwd: false
    ssh_pwauth: true
    chpasswd: { expire: false }

package_upgrade: false

# # Set the locale of the system
locale: "de_AT.UTF-8"

# # Set the timezone
# # Value of 'timezone' must exist in /usr/share/zoneinfo
timezone: "Europe/Vienna"

# # Update apt packages on first boot
# package_update: true
# package_upgrade: trueloca
# package_reboot_if_required: true
package_upgrade: false

# # Install any additional apt packages you need here
packages:
  - ntp

# # WiFi connect to HotSpot
# To make wifi work with RPi3 and RPi0
# you also have to set "enable_uart=0" in config.txt
# See no-uart-config.txt for an example.
#
# # - use `wpa_passphrase SSID PASSWORD` to encrypt the psk
write_files:
  - content: |
      allow-hotplug wlan0
      iface wlan0 inet dhcp
      wpa-conf /etc/wpa_supplicant/wpa_supplicant.conf
      iface default inet dhcp
    path: /etc/network/interfaces.d/wlan0
  - content: |
      country=YourContryCode
      ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
      update_config=1
      network={
      ssid="MyNetworkName"
      psk="MyPassword"
      proto=RSN
      key_mgmt=WPA-PSK
      pairwise=CCMP
      auth_alg=OPEN
      }
    path: /etc/wpa_supplicant/wpa_supplicant.conf
# These commands will be ran once on first boot only
runcmd:
  # Pickup the hostname changes
  - 'systemctl restart avahi-daemon'
  # Activate WiFi interface
  - 'ifup wlan0'

bootcmd:
 - [ ifup, wlan0 ]
```

I now try to figure out how to install it and will report!
